export const styles = {
  headerContainer: {
    margin: "auto",
    width: "1600px",
    height: "772px",
  },
  headerTextContainer: {
    display: "flex",
    flexDirection: "column",
    width: "651px",
    gap: "20px",
    marginTop: "130px",
  },
  headerFont: {
    fontFamily: "'Poppins', sans-serif",
    fontSize: "77px",
    fontWeight: "700",
    color: "#262338",
    lineHeight: "120px",
  },
  description: {
    fontFamily: "'Poppins', sans-serif",
    fontSize: "24px",
    color: "#262338",
    fontWeight: 350,
  },
  buttonContainer: {
    display: "flex",
    alignItems: "center",
    gap: "38px",
    marginTop: "90px",
  },
  startButton: {
    textTransform: "none",
    background: "linear-gradient(90deg, #0C0A3E 0%, #3E92CC 100.15%)",
    color: "white",
    boxShadow: 0,
    fontFamily: "'Poppins', sans-serif",
    fontSize: "22px",
    padding: "24px 80px",
    borderRadius: "15px",
    "&:hover": {
      color: "#2a2b36",
    },
  },
  learnButton: {
    textTransform: "none",
    border: "1px solid #0C0A3E",
    backgroundColor: "white",
    color: "#0C0A3E",
    boxShadow: 0,
    fontFamily: "'Poppins', sans-serif",
    fontSize: "22px",
    padding: "23px 60px",
    borderRadius: "15px",
    display: "flex",
    gap: "10px",
    "&:hover": {
      backgroundColor: "#d9dbe9",
      border: "1px solid #d9dbe9",
      boxShadow: 0,
    },
  },
};
